"""
Seed provider data for CivicReach Locator. Run: python -m scripts.seed_providers
Uses Mumbai-area coordinates; spread so radius filters return varied results.
"""
import os
import sys
from datetime import date, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pymongo import MongoClient

# Base: Bandra West (Mumbai). Offsets in ~0.001–0.015 deg (~100m–1.5km) for variety.
BASE_LNG, BASE_LAT = 72.8273, 19.0596

PROVIDERS = [
    # Tailors
    {
        "name": "Mehboob Tailoring House",
        "service_type": "tailor",
        "description": "Custom stitching, alterations, and ethnic wear. Family-run since 1989.",
        "address": "Linking Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.002, BASE_LAT + 0.001]},
        "community_photos_count": 14,
        "confirmations_count": 28,
        "phone": "+91 98201 23456",
        "photo_urls": [],
        "years_in_business": 35,
        "last_verified": (date.today() - timedelta(days=12)).isoformat(),
        "opening_hours": ["Mon–Sat: 10:00–20:00", "Sun: 10:00–14:00"],
        "services_offered": ["Alterations", "Custom stitching", "Bridal wear", "Formal wear", "Ethnic wear"],
    },
    {
        "name": "Raju Master Tailor",
        "service_type": "tailor",
        "description": "Quick alterations and school uniform stitching. Walk-ins welcome.",
        "address": "Hill Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.001, BASE_LAT + 0.002]},
        "community_photos_count": 8,
        "confirmations_count": 19,
        "phone": "+91 98765 43210",
        "photo_urls": [],
        "years_in_business": 22,
        "last_verified": (date.today() - timedelta(days=5)).isoformat(),
        "opening_hours": ["Mon–Sat: 9:00–19:30", "Sun: Closed"],
        "services_offered": ["Alterations", "School uniforms", "Shirts", "Trousers"],
    },
    {
        "name": "Stitch & Style",
        "service_type": "tailor",
        "description": "Modern tailoring with same-day alterations on select items.",
        "address": "Carter Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.008, BASE_LAT - 0.003]},
        "community_photos_count": 6,
        "confirmations_count": 11,
        "phone": "+91 97654 32109",
        "photo_urls": [],
        "years_in_business": 7,
        "last_verified": (date.today() - timedelta(days=21)).isoformat(),
        "opening_hours": ["Mon–Fri: 10:00–19:00", "Sat: 10:00–16:00", "Sun: Closed"],
        "services_offered": ["Alterations", "Custom blazers", "Western wear"],
    },
    {
        "name": "Khan Brothers Tailors",
        "service_type": "tailor",
        "description": "Sherwani, suit, and wedding wear specialists.",
        "address": "Lane 5, Pali Hill, Bandra West",
        "area": "Pali Hill",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.003, BASE_LAT + 0.005]},
        "community_photos_count": 11,
        "confirmations_count": 24,
        "phone": "+91 98192 33445",
        "photo_urls": [],
        "years_in_business": 18,
        "last_verified": (date.today() - timedelta(days=8)).isoformat(),
        "opening_hours": ["Mon–Sat: 9:30–19:00", "Sun: By appointment"],
        "services_offered": ["Sherwani", "Suits", "Wedding wear", "Alterations", "Blazers"],
    },
    {
        "name": "Laxmi Tailors",
        "service_type": "tailor",
        "description": "Saree blouse stitching and traditional wear.",
        "address": "Linking Road Market, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.0015, BASE_LAT + 0.0005]},
        "community_photos_count": 9,
        "confirmations_count": 17,
        "phone": None,
        "photo_urls": [],
        "years_in_business": 12,
        "last_verified": (date.today() - timedelta(days=15)).isoformat(),
        "opening_hours": ["Mon–Sat: 10:00–20:00", "Sun: 11:00–17:00"],
        "services_offered": ["Saree blouses", "Choli", "Traditional wear", "Alterations"],
    },
    # Electricians
    {
        "name": "Sharma Electrical Works",
        "service_type": "electrician",
        "description": "Residential and small commercial wiring, fan and fixture installation.",
        "address": "S.V. Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.002, BASE_LAT - 0.001]},
        "community_photos_count": 7,
        "confirmations_count": 16,
        "phone": "+91 98921 44556",
        "photo_urls": [],
        "years_in_business": 20,
        "last_verified": (date.today() - timedelta(days=3)).isoformat(),
        "opening_hours": ["Mon–Sat: 8:00–18:00", "Sun: Emergency only"],
        "services_offered": ["Wiring", "Fan installation", "Light fixtures", "Switch repair", "MCB"],
    },
    {
        "name": "Bandra Electric Co.",
        "service_type": "electrician",
        "description": "Licensed electrician for home and office. Same-day service available.",
        "address": "Waterfield Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.004, BASE_LAT + 0.003]},
        "community_photos_count": 12,
        "confirmations_count": 31,
        "phone": "+91 98203 55667",
        "photo_urls": [],
        "years_in_business": 14,
        "last_verified": (date.today() - timedelta(days=1)).isoformat(),
        "opening_hours": ["Mon–Sat: 9:00–18:00", "Sun: 10:00–14:00"],
        "services_offered": ["Full wiring", "Inverter setup", "LED installation", "DB repair", "Earthing"],
    },
    {
        "name": "Prakash Electrician",
        "service_type": "electrician",
        "description": "Fault finding, rewiring, and appliance repair.",
        "address": "Chimbai Road, Bandra West",
        "area": "Chimbai",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.006, BASE_LAT - 0.002]},
        "community_photos_count": 5,
        "confirmations_count": 9,
        "phone": "+91 97654 11223",
        "photo_urls": [],
        "years_in_business": 9,
        "last_verified": (date.today() - timedelta(days=18)).isoformat(),
        "opening_hours": ["Mon–Sat: 8:00–17:00", "Sun: Closed"],
        "services_offered": ["Fault finding", "Rewiring", "Appliance repair", "Switchboard"],
    },
    {
        "name": "SafeWire Electrical",
        "service_type": "electrician",
        "description": "Safety-first residential electrical work. Insured.",
        "address": "Perry Cross Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.005, BASE_LAT + 0.004]},
        "community_photos_count": 10,
        "confirmations_count": 22,
        "phone": "+91 98188 99887",
        "photo_urls": [],
        "years_in_business": 11,
        "last_verified": (date.today() - timedelta(days=7)).isoformat(),
        "opening_hours": ["Mon–Sat: 9:00–19:00", "Sun: Emergency only"],
        "services_offered": ["Safe wiring", "RCCB installation", "Surge protection", "Lighting"],
    },
    # Cobblers
    {
        "name": "Mohan Shoe Repair",
        "service_type": "cobbler",
        "description": "Sole replacement, heel repair, polish, and key cutting.",
        "address": "Linking Road footpath, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.003, BASE_LAT + 0.0015]},
        "community_photos_count": 15,
        "confirmations_count": 34,
        "phone": None,
        "photo_urls": [],
        "years_in_business": 28,
        "last_verified": (date.today() - timedelta(days=4)).isoformat(),
        "opening_hours": ["Mon–Sat: 8:00–20:00", "Sun: 9:00–18:00"],
        "services_offered": ["Sole replacement", "Heel repair", "Polish", "Key cutting", "Bag repair"],
    },
    {
        "name": "Quick Fix Cobbler",
        "service_type": "cobbler",
        "description": "Fast sole and heel fixes. Same-day service for most repairs.",
        "address": "Hill Road, Bandra West",
        "area": "Bandra West",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.0005, BASE_LAT + 0.003]},
        "community_photos_count": 6,
        "confirmations_count": 13,
        "phone": "+91 98765 44332",
        "photo_urls": [],
        "years_in_business": 6,
        "last_verified": (date.today() - timedelta(days=11)).isoformat(),
        "opening_hours": ["Mon–Sun: 9:00–19:00"],
        "services_offered": ["Sole repair", "Heel fix", "Polish", "Strap repair"],
    },
    {
        "name": "Leather & Sole",
        "service_type": "cobbler",
        "description": "Leather restoration, premium polish, and shoe stretching.",
        "address": "Pali Naka, Bandra West",
        "area": "Pali Naka",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.004, BASE_LAT + 0.006]},
        "community_photos_count": 8,
        "confirmations_count": 18,
        "phone": "+91 97651 22334",
        "photo_urls": [],
        "years_in_business": 16,
        "last_verified": (date.today() - timedelta(days=9)).isoformat(),
        "opening_hours": ["Mon–Sat: 10:00–19:00", "Sun: Closed"],
        "services_offered": ["Leather repair", "Premium polish", "Shoe stretching", "Sole replacement"],
    },
    {
        "name": "Ramesh Cobbler",
        "service_type": "cobbler",
        "description": "Affordable shoe repair and chappal stitching.",
        "address": "Chimbai Beach Road, Bandra West",
        "area": "Chimbai",
        "location": {"type": "Point", "coordinates": [BASE_LNG + 0.007, BASE_LAT - 0.001]},
        "community_photos_count": 4,
        "confirmations_count": 7,
        "phone": None,
        "photo_urls": [],
        "years_in_business": 19,
        "last_verified": (date.today() - timedelta(days=25)).isoformat(),
        "opening_hours": ["Mon–Sat: 8:00–18:00", "Sun: 8:00–14:00"],
        "services_offered": ["Sole repair", "Chappal stitching", "Polish", "Heel repair"],
    },
    # More spread (slightly farther)
    {
        "name": "Supreme Tailors",
        "service_type": "tailor",
        "description": "Bulk orders for uniforms and corporate wear.",
        "address": "Khar West, S.V. Road",
        "area": "Khar West",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.012, BASE_LAT - 0.002]},
        "community_photos_count": 5,
        "confirmations_count": 10,
        "phone": "+91 98211 77889",
        "photo_urls": [],
        "years_in_business": 8,
        "last_verified": (date.today() - timedelta(days=14)).isoformat(),
        "opening_hours": ["Mon–Fri: 9:00–18:00", "Sat: 9:00–14:00", "Sun: Closed"],
        "services_offered": ["Corporate uniforms", "Bulk stitching", "Alterations"],
    },
    {
        "name": "Javed Electric Works",
        "service_type": "electrician",
        "description": "Generator and inverter installation and repair.",
        "address": "Santacruz West, near station",
        "area": "Santacruz West",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.018, BASE_LAT + 0.001]},
        "community_photos_count": 9,
        "confirmations_count": 20,
        "phone": "+91 98902 33441",
        "photo_urls": [],
        "years_in_business": 13,
        "last_verified": (date.today() - timedelta(days=6)).isoformat(),
        "opening_hours": ["Mon–Sat: 8:00–18:00", "Sun: Emergency only"],
        "services_offered": ["Generator", "Inverter", "Wiring", "DB panel"],
    },
    {
        "name": "Babulal Shoe Works",
        "service_type": "cobbler",
        "description": "School shoe repair and canvas stitching.",
        "address": "Vile Parle East, near station",
        "area": "Vile Parle East",
        "location": {"type": "Point", "coordinates": [BASE_LNG - 0.025, BASE_LAT - 0.003]},
        "community_photos_count": 7,
        "confirmations_count": 14,
        "phone": None,
        "photo_urls": [],
        "years_in_business": 24,
        "last_verified": (date.today() - timedelta(days=10)).isoformat(),
        "opening_hours": ["Mon–Sat: 8:00–19:00", "Sun: 8:00–12:00"],
        "services_offered": ["School shoes", "Canvas repair", "Sole", "Polish"],
    },
]

MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://localhost:27017")
DB_NAME = os.getenv("DB_NAME", "civicreach")


def main():
    client = MongoClient(MONGODB_URI)
    db = client[DB_NAME]
    coll = db["providers"]
    coll.delete_many({})
    coll.insert_many(PROVIDERS)
    coll.create_index([("location", "2dsphere")])
    coll.create_index([("service_type", 1)])
    print(f"Inserted {len(PROVIDERS)} providers into {DB_NAME}.providers")


if __name__ == "__main__":
    main()
